apiVersion: v1
kind: Service
metadata:
  name: nginx-flask-service
spec:
  type: NodePort
  ports:
    -
      port: 8080
      targetPort: 80
      nodePort: 30061
  selector:
    app: nginx-flask-pod
