
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-flask-controller
spec:
  replicas: 2
  selector:
    app: nginx-flask-pod
  template:
    metadata:
      labels:
        app: nginx-flask-pod
    spec:
      containers:
      - name: kubernetes-demo-nginx
        image: adimania/nginx_pp_5000
        command:
          - /opt/run.sh
        ports:
          - containerPort: 80
            targetPort: 80
      - name: kubernetes-demo-flask
        image: adimania/demo-app
        ports:
          - containerPort: 5000
